# Theme
remote_theme: epidrome/cover-card@main

# Site Settings
title: 'Dr. Florian Geigl'
description: 'K8s Product Manager Dynatrace. PhD in ComputerScience. K8s, DataScience, MachineLearning & Python enthusiast. Loves reading. Opinions are my own.'

# Online profiles
# surfer: 'surfer.epidro.me'
# scholar: 'scholar.epidro.me'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

social-links-order: [Email,Twitter,GitHub,LinkedIn]

social-links:
  - name: Email 
    url-pattern: 'florian.geigl+githubpage@gmail.com'
    url-scheme: 'mailto://'
    icon-class: fas fa-envelope

  - name: Twitter 
    url-pattern: 'twitter.com/floriangeigl'
    url-scheme: 'https://'
    icon-class: fab fa-twitter
  
  - name: LinkedIn 
    url-pattern: 'www.linkedin.com/in/floriangeigl/'
    url-scheme: 'https://'
    icon-class: fab fa-linkedin
    
  - name: GitHub 
    url-pattern: 'github.com/floriangeigl'
    url-scheme: 'https://'
    icon-class: fab fa-github
